# Resolucion SUDOKU por DNN

Functions Definition

In [1]:
import numpy as np
import pandas as pd
from tensorflow.contrib.keras import utils

In [2]:
def load_data(nb_train=40000, nb_test=10000, full=False):
    """
    Function to load data in the keras way.
    
    Parameters
    ----------
    nb_train (int): Number of training examples
    nb_test (int): Number of testing examples
    full (bool): If True, whole csv will be loaded, nb_test will be ignored
    
    Returns
    -------
    Xtrain, ytrain (np.array, np.array),
        shapes (nb_train, 9, 9), (nb_train, 9, 9): Training samples
    Xtest, ytest (np.array, np.array), 
        shapes (nb_test, 9, 9), (nb_test, 9, 9): Testing samples
    """
    # if full is true, load the whole dataset
    if full:
        sudokus = pd.read_csv('../input/sudoku.csv').values
    else:
        sudokus = next(
            pd.read_csv('D:\Work\sudoku.csv', chunksize=(nb_train + nb_test))
        ).values
        
    
    quizzes, solutions = sudokus.T
    
          
    
    flatX = np.array([np.reshape([int(d) for d in flatten_grid], (9, 9))
                      for flatten_grid in quizzes])
    flaty = np.array([np.reshape([int(d) for d in flatten_grid], (9, 9))
                      for flatten_grid in solutions])
    
    return (flatX[:nb_train], flaty[:nb_train]), (flatX[nb_train:], flaty[nb_train:])

(Xtrain, ytrain), (Xtest, ytest) = load_data(1,1,False)  # We won't use _. We will work directly with ytrain

print (ytrain)
print (Xtrain)
print (ytrain.shape)
print (Xtrain.shape)



[[[8 6 4 3 7 1 2 5 9]
  [3 2 5 8 4 9 7 6 1]
  [9 7 1 2 6 5 8 4 3]
  [4 3 6 1 9 2 5 8 7]
  [1 9 8 6 5 7 4 3 2]
  [2 5 7 4 8 3 9 1 6]
  [6 8 9 7 3 4 1 2 5]
  [7 1 3 5 2 8 6 9 4]
  [5 4 2 9 1 6 3 7 8]]]
[[[0 0 4 3 0 0 2 0 9]
  [0 0 5 0 0 9 0 0 1]
  [0 7 0 0 6 0 0 4 3]
  [0 0 6 0 0 2 0 8 7]
  [1 9 0 0 0 7 4 0 0]
  [0 5 0 0 8 3 0 0 0]
  [6 0 0 0 0 0 1 0 5]
  [0 0 3 5 0 8 6 9 0]
  [0 4 2 9 1 0 3 0 0]]]
(1, 9, 9)
(1, 9, 9)


In [3]:
def delete_digits(X, n_delet=1):
    """
    This function is used to create sudoku quizzes from solutions
    
    Parameters
    ----------
    X (np.array), shape (?, 9, 9, 9|10): input solutions grids.
    n_delet (integer): max number of digit to suppress from original solutions
    
    Returns
    -------
    grids: np.array of grids to guess in one-hot way. Shape: (?, 9, 9, 10)
    """
    grids = X.argmax(3)  # get the grid in a (9, 9) integer shape
    for grid in grids:
        grid.flat[np.random.randint(0, 81, n_delet)] = 0  # generate blanks (replace = True)
        
    return np.reshape(utils.to_categorical(grids), (-1,9,9,10))

In [4]:
def diff(grids_true, grids_pred):
    """
    This function shows how well predicted quizzes fit to actual solutions.
    It will store sum of differences for each pair (solution, guess)
    
    Parameters
    ----------
    grids_true (np.array), shape (?, 9, 9): Real solutions to guess in the digit repesentation
    grids_pred (np.array), shape (?, 9, 9): Guesses
    
    Returns
    -------
    diff (np.array), shape (?,): Number of differences for each pair (solution, guess)
    """
    return (grids_true != grids_pred).sum((1, 2))

def batch_smart_solve(grids, solver):
    """
    NOTE : This function is ugly, feel free to optimize the code ...
    
    This function solves quizzes in the "smart" way. 
    It will fill blanks one after the other. Each time a digit is filled, 
    the new grid will be fed again to the solver to predict the next digit. 
    Again and again, until there is no more blank
    
    Parameters
    ----------
    grids (np.array), shape (?, 9, 9): Batch of quizzes to solve (smartly ;))
    solver (keras.model): The neural net solver
    
    Returns
    -------
    grids (np.array), shape (?, 9, 9): Smartly solved quizzes.
    """
    grids = grids.copy()
    for _ in range((grids == 0).sum((1, 2)).max()):
        preds = np.array(solver.predict(np.reshape(utils.to_categorical(grids), (-1,9,9,10))))  # get predictions
        probs = preds.max(2).T  # get highest probability for each 81 digit to predict
        values = preds.argmax(2).T + 1  # get corresponding values
        zeros = (grids == 0).reshape((grids.shape[0], 81))  # get blank positions

        for grid, prob, value, zero in zip(grids, probs, values, zeros):
            if any(zero):  # don't try to fill already completed grid
                where = np.where(zero)[0]  # focus on blanks only
                confidence_position = where[prob[zero].argmax()]  # best score FOR A ZERO VALUE (confident blank)
                confidence_value = value[confidence_position]  # get corresponding value
                grid.flat[confidence_position] = confidence_value  # fill digit inplace
    return grids


Prepare data for the training phase.

In [16]:
input_shape = (9, 9, 10)
(_, ytrain), (Xtest, ytest) = load_data()  # We won't use _. We will work directly with ytrain

# one-hot-encoding --> shapes become :
# (?, 9, 9, 10) for Xs
# (?, 9, 9, 9) for ys

Xtrain = utils.to_categorical(ytrain).astype('float32')  # from ytrain cause we will creates quizzes from solusions
Xtest = utils.to_categorical(Xtest).astype('float32')
XtestTrue = utils.to_categorical(ytest).astype('float32')

ytest_true = np.copy(ytest)
ytrain = utils.to_categorical(ytrain-1).astype('float32') # (y - 1) because we 
ytest = utils.to_categorical(ytest-1).astype('float32')   # don't want to predict zeros




ytrain=np.reshape(ytrain, (-1,9,9,9))
Xtrain=np.reshape(Xtrain, (-1,9,9,10))
ytest=np.reshape(ytest, (-1,9,9,9))
Xtest=np.reshape(Xtest, (-1,9,9,10))
XtestTrue=np.reshape(XtestTrue, (-1,9,9,10))



# TensorFlow Keras

### Create the Model

In [6]:
from tensorflow.contrib.keras import models

In [7]:
dnn_keras_model = models.Sequential()

### Add Layers to the model

In [8]:
from tensorflow.contrib.keras import layers

In [9]:
input_shape = (9,9,10)

In [10]:
dnn_keras_model.add(layers.Dense(units=64,input_shape=input_shape,activation='relu'))

W0902 19:45:15.112726  8628 deprecation.py:506] From C:\Anaconda\envs\tensorflow_env\lib\site-packages\tensorflow\python\ops\init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [11]:
dnn_keras_model.add(layers.Dropout(0.4))
dnn_keras_model.add(layers.Dense(units=64,activation='relu'))
dnn_keras_model.add(layers.Dropout(0.4))
dnn_keras_model.add(layers.Flatten())

In [12]:
grid = layers.Input(shape=input_shape)
features = dnn_keras_model(grid)
digit_placeholders = [ 
    layers.Dense(9, activation='softmax')(features)
    for i in range(81)
]

solver = models.Model (grid, digit_placeholders)

In [13]:
print(solver.summary())
#from tensorflow.contrib.keras import utils
#import graphviz 
#import pydotplus 
#utils.pydot = pydotplus
#utils.plot_model(solver, to_file='model_plot2.png', show_shapes=True, show_layer_names=True)

Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 9, 9, 10)]   0                                            
__________________________________________________________________________________________________
sequential (Sequential)         (None, 5184)         4864        input_1[0][0]                    
__________________________________________________________________________________________________
dense_2 (Dense)                 (None, 9)            46665       sequential[1][0]                 
__________________________________________________________________________________________________
dense_3 (Dense)                 (None, 9)            46665       sequential[1][0]                 
______________________________________________________________________________________________

### Compile the Model

In [14]:
from tensorflow.contrib.keras import losses,optimizers,metrics, callbacks

In [15]:
solver.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

### Train Model

In [17]:
solver.fit(
    delete_digits(Xtrain, 0),  # we don't delete any digit for now
    [ytrain[:, i, j, :] for i in range(9) for j in range(9)],  # each digit of solution
    batch_size=128,
    epochs=1,  # 1 epoch should be enough for the task
    verbose=1,
)

40000/40000 [==============================] - 102s 3ms/sample - loss: 43.1880 - dense_2_loss: 0.5314 - dense_3_loss: 0.5356 - dense_4_loss: 0.5240 - dense_5_loss: 0.5321 - dense_6_loss: 0.5332 - dense_7_loss: 0.5314 - dense_8_loss: 0.5289 - dense_9_loss: 0.5285 - dense_10_loss: 0.5295 - dense_11_loss: 0.5321 - dense_12_loss: 0.5362 - dense_13_loss: 0.5353 - dense_14_loss: 0.5355 - dense_15_loss: 0.5288 - dense_16_loss: 0.5335 - dense_17_loss: 0.5323 - dense_18_loss: 0.5423 - dense_19_loss: 0.5360 - dense_20_loss: 0.5294 - dense_21_loss: 0.5353 - dense_22_loss: 0.5368 - dense_23_loss: 0.5331 - dense_24_loss: 0.5337 - dense_25_loss: 0.5308 - dense_26_loss: 0.5246 - dense_27_loss: 0.5296 - dense_28_loss: 0.5313 - dense_29_loss: 0.5311 - dense_30_loss: 0.5424 - dense_31_loss: 0.5382 - dense_32_loss: 0.5340 - dense_33_loss: 0.5298 - dense_34_loss: 0.5340 - dense_35_loss: 0.5275 - dense_36_loss: 0.5374 - dense_37_loss: 0.5265 - dense_38_loss: 0.5321 - dense_39_loss: 0.5259 - dense_40_loss: 

In [17]:
# evaluate the model
scores = solver.evaluate(
    delete_digits(XtestTrue, 1),  # we don't delete any digit for now
    [ytest[:, i, j, :] for i in range(9) for j in range(9)],
    verbose=0)

In [18]:
for n in range(81):
    print("%s: %.2f%%" % (solver.metrics_names[n], scores[n]*100))

loss: 17891.50%
dense_2_loss: 220.83%
dense_3_loss: 220.86%
dense_4_loss: 220.14%
dense_5_loss: 221.06%
dense_6_loss: 221.51%
dense_7_loss: 221.07%
dense_8_loss: 221.73%
dense_9_loss: 220.97%
dense_10_loss: 220.09%
dense_11_loss: 221.28%
dense_12_loss: 221.14%
dense_13_loss: 220.51%
dense_14_loss: 220.70%
dense_15_loss: 220.60%
dense_16_loss: 221.86%
dense_17_loss: 220.83%
dense_18_loss: 222.58%
dense_19_loss: 220.69%
dense_20_loss: 220.67%
dense_21_loss: 220.04%
dense_22_loss: 220.46%
dense_23_loss: 220.14%
dense_24_loss: 220.37%
dense_25_loss: 221.44%
dense_26_loss: 220.57%
dense_27_loss: 221.54%
dense_28_loss: 220.50%
dense_29_loss: 219.97%
dense_30_loss: 221.55%
dense_31_loss: 220.95%
dense_32_loss: 220.83%
dense_33_loss: 220.73%
dense_34_loss: 221.26%
dense_35_loss: 219.68%
dense_36_loss: 221.27%
dense_37_loss: 221.03%
dense_38_loss: 220.91%
dense_39_loss: 220.65%
dense_40_loss: 220.16%
dense_41_loss: 221.40%
dense_42_loss: 220.78%
dense_43_loss: 220.87%
dense_44_loss: 220.52%
den

In [20]:
solver.save("d:\model_solverv2.h5")
print("Saved model to disk")

Saved model to disk


In [22]:
solver = models.load_model('model_solver.h5')

In [72]:
xpredict = delete_digits(XtestTrue, 2)
predictions = solver.predict(xpredict)

In [73]:
print ('*'*50,'valores originales')
values = xpredict.argmax(3)
print(values)

preds = np.array(predictions)
#print ('shape prediction=', preds.shape)
values = preds.argmax(2).T + 1 
#print ('shape values original=', values.shape)
values = np.reshape(np.array(values), (-1,9,9))

print('*'*50, 'valores Predichos')
print(values)

print('*'*50, 'valores Realess')
print(ytest_true)



#zeros = (grids == 0).reshape((grids.shape[0], 81))  # get blank positions
#print(zeros)

************************************************** valores originales
[[[6 9 5 1 0 7 3 8 4]
  [1 3 8 4 0 9 6 7 2]
  [7 2 4 8 3 6 9 1 5]
  [8 5 1 2 6 4 7 3 9]
  [2 7 3 9 8 1 5 4 6]
  [9 4 6 5 7 3 8 2 1]
  [3 1 7 6 9 2 4 5 8]
  [4 8 9 7 1 5 2 6 3]
  [5 6 2 3 4 8 1 9 7]]

 [[0 9 7 2 5 8 3 1 6]
  [1 8 6 4 3 9 7 2 5]
  [2 5 3 7 1 6 4 9 8]
  [6 2 9 3 8 1 5 4 7]
  [3 7 5 9 6 4 1 8 2]
  [8 4 1 5 7 2 6 3 9]
  [9 6 2 1 4 5 8 7 3]
  [7 1 8 6 2 3 9 5 4]
  [5 0 4 8 9 7 2 6 1]]]
************************************************** valores Predichos
[[[6 9 5 1 5 7 3 8 4]
  [1 3 8 4 5 9 6 7 2]
  [7 2 4 8 3 6 9 1 5]
  [8 5 1 2 6 4 7 3 9]
  [2 7 3 9 8 1 5 4 6]
  [9 4 6 5 7 3 8 2 1]
  [3 1 7 6 9 2 4 5 8]
  [4 8 9 7 1 5 2 6 3]
  [5 6 2 3 4 8 1 9 7]]

 [[4 9 7 2 5 8 3 1 6]
  [1 8 6 4 3 9 7 2 5]
  [2 5 3 7 1 6 4 9 8]
  [6 2 9 3 8 1 5 4 7]
  [3 7 5 9 6 4 1 8 2]
  [8 4 1 5 7 2 6 3 9]
  [9 6 2 1 4 5 8 7 3]
  [7 1 8 6 2 3 9 5 4]
  [5 3 4 8 9 7 2 6 1]]]
************************************************** valores Re

In [19]:

early_stop = callbacks.EarlyStopping(patience=2, verbose=1)

i = 1
for nb_epochs, nb_delete in zip(
        [1, 2, 3, 4, 6, 8, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10],  # epochs for each round (17)
        [1, 2, 3, 4, 6, 8, 10, 12, 15, 20, 25, 30, 35, 40, 45, 50, 55]  # digit to pull off
):
    print('Pass n° {} ...'.format(i))
    i += 1
    
    solver.fit(
        delete_digits(Xtrain, nb_delete),  # delete digits from training sample
        [ytrain[:, i, j, :] for i in range(9) for j in range(9)],
        validation_data=(
            delete_digits(Xtrain, nb_delete), # delete same amount of digit from validation sample
            [ytrain[:, i, j, :] for i in range(9) for j in range(9)]),
        batch_size=128,
        epochs=nb_epochs,
        verbose=1,
        callbacks=[early_stop]
    )


Pass n° 1 ...
Train on 40000 samples, validate on 40000 samples
40000/40000 [==============================] - 109s 3ms/sample - loss: 1.2475 - dense_2_loss: 0.0142 - dense_3_loss: 0.0167 - dense_4_loss: 0.0151 - dense_5_loss: 0.0155 - dense_6_loss: 0.0156 - dense_7_loss: 0.0147 - dense_8_loss: 0.0141 - dense_9_loss: 0.0169 - dense_10_loss: 0.0166 - dense_11_loss: 0.0149 - dense_12_loss: 0.0163 - dense_13_loss: 0.0157 - dense_14_loss: 0.0156 - dense_15_loss: 0.0165 - dense_16_loss: 0.0146 - dense_17_loss: 0.0148 - dense_18_loss: 0.0168 - dense_19_loss: 0.0155 - dense_20_loss: 0.0162 - dense_21_loss: 0.0151 - dense_22_loss: 0.0154 - dense_23_loss: 0.0145 - dense_24_loss: 0.0157 - dense_25_loss: 0.0153 - dense_26_loss: 0.0157 - dense_27_loss: 0.0159 - dense_28_loss: 0.0148 - dense_29_loss: 0.0153 - dense_30_loss: 0.0154 - dense_31_loss: 0.0153 - dense_32_loss: 0.0147 - dense_33_loss: 0.0156 - dense_34_loss: 0.0152 - dense_35_loss: 0.0156 - dense_36_loss: 0.0155 - dense_37_loss: 0.0150 - 

Pass n° 2 ...
Train on 40000 samples, validate on 40000 samples
Epoch 1/2
40000/40000 [==============================] - 105s 3ms/sample - loss: 1.4786 - dense_2_loss: 0.0172 - dense_3_loss: 0.0165 - dense_4_loss: 0.0180 - dense_5_loss: 0.0215 - dense_6_loss: 0.0179 - dense_7_loss: 0.0194 - dense_8_loss: 0.0179 - dense_9_loss: 0.0182 - dense_10_loss: 0.0190 - dense_11_loss: 0.0161 - dense_12_loss: 0.0193 - dense_13_loss: 0.0143 - dense_14_loss: 0.0180 - dense_15_loss: 0.0180 - dense_16_loss: 0.0187 - dense_17_loss: 0.0195 - dense_18_loss: 0.0175 - dense_19_loss: 0.0179 - dense_20_loss: 0.0208 - dense_21_loss: 0.0190 - dense_22_loss: 0.0192 - dense_23_loss: 0.0204 - dense_24_loss: 0.0198 - dense_25_loss: 0.0210 - dense_26_loss: 0.0188 - dense_27_loss: 0.0173 - dense_28_loss: 0.0195 - dense_29_loss: 0.0195 - dense_30_loss: 0.0176 - dense_31_loss: 0.0152 - dense_32_loss: 0.0174 - dense_33_loss: 0.0190 - dense_34_loss: 0.0183 - dense_35_loss: 0.0184 - dense_36_loss: 0.0193 - dense_37_loss:

Epoch 2/2
40000/40000 [==============================] - 114s 3ms/sample - loss: 1.0465 - dense_2_loss: 0.0121 - dense_3_loss: 0.0114 - dense_4_loss: 0.0115 - dense_5_loss: 0.0122 - dense_6_loss: 0.0108 - dense_7_loss: 0.0137 - dense_8_loss: 0.0137 - dense_9_loss: 0.0134 - dense_10_loss: 0.0120 - dense_11_loss: 0.0126 - dense_12_loss: 0.0125 - dense_13_loss: 0.0109 - dense_14_loss: 0.0130 - dense_15_loss: 0.0136 - dense_16_loss: 0.0137 - dense_17_loss: 0.0135 - dense_18_loss: 0.0136 - dense_19_loss: 0.0116 - dense_20_loss: 0.0162 - dense_21_loss: 0.0125 - dense_22_loss: 0.0130 - dense_23_loss: 0.0121 - dense_24_loss: 0.0104 - dense_25_loss: 0.0162 - dense_26_loss: 0.0133 - dense_27_loss: 0.0122 - dense_28_loss: 0.0134 - dense_29_loss: 0.0147 - dense_30_loss: 0.0129 - dense_31_loss: 0.0124 - dense_32_loss: 0.0142 - dense_33_loss: 0.0119 - dense_34_loss: 0.0128 - dense_35_loss: 0.0126 - dense_36_loss: 0.0124 - dense_37_loss: 0.0129 - dense_38_loss: 0.0113 - dense_39_loss: 0.0148 - dense_

Pass n° 3 ...
Train on 40000 samples, validate on 40000 samples
Epoch 1/3
40000/40000 [==============================] - 107s 3ms/sample - loss: 1.7165 - dense_2_loss: 0.0254 - dense_3_loss: 0.0207 - dense_4_loss: 0.0207 - dense_5_loss: 0.0185 - dense_6_loss: 0.0205 - dense_7_loss: 0.0201 - dense_8_loss: 0.0210 - dense_9_loss: 0.0226 - dense_10_loss: 0.0208 - dense_11_loss: 0.0213 - dense_12_loss: 0.0212 - dense_13_loss: 0.0192 - dense_14_loss: 0.0243 - dense_15_loss: 0.0207 - dense_16_loss: 0.0191 - dense_17_loss: 0.0218 - dense_18_loss: 0.0208 - dense_19_loss: 0.0211 - dense_20_loss: 0.0192 - dense_21_loss: 0.0234 - dense_22_loss: 0.0222 - dense_23_loss: 0.0232 - dense_24_loss: 0.0195 - dense_25_loss: 0.0204 - dense_26_loss: 0.0210 - dense_27_loss: 0.0226 - dense_28_loss: 0.0200 - dense_29_loss: 0.0199 - dense_30_loss: 0.0199 - dense_31_loss: 0.0231 - dense_32_loss: 0.0220 - dense_33_loss: 0.0232 - dense_34_loss: 0.0232 - dense_35_loss: 0.0206 - dense_36_loss: 0.0205 - dense_37_loss:

Epoch 2/3
40000/40000 [==============================] - 104s 3ms/sample - loss: 1.0981 - dense_2_loss: 0.0171 - dense_3_loss: 0.0123 - dense_4_loss: 0.0145 - dense_5_loss: 0.0132 - dense_6_loss: 0.0125 - dense_7_loss: 0.0134 - dense_8_loss: 0.0122 - dense_9_loss: 0.0133 - dense_10_loss: 0.0144 - dense_11_loss: 0.0145 - dense_12_loss: 0.0125 - dense_13_loss: 0.0146 - dense_14_loss: 0.0135 - dense_15_loss: 0.0117 - dense_16_loss: 0.0142 - dense_17_loss: 0.0139 - dense_18_loss: 0.0141 - dense_19_loss: 0.0144 - dense_20_loss: 0.0138 - dense_21_loss: 0.0150 - dense_22_loss: 0.0142 - dense_23_loss: 0.0132 - dense_24_loss: 0.0167 - dense_25_loss: 0.0119 - dense_26_loss: 0.0152 - dense_27_loss: 0.0132 - dense_28_loss: 0.0111 - dense_29_loss: 0.0115 - dense_30_loss: 0.0118 - dense_31_loss: 0.0151 - dense_32_loss: 0.0121 - dense_33_loss: 0.0149 - dense_34_loss: 0.0121 - dense_35_loss: 0.0161 - dense_36_loss: 0.0128 - dense_37_loss: 0.0140 - dense_38_loss: 0.0153 - dense_39_loss: 0.0141 - dense_

Epoch 3/3
40000/40000 [==============================] - 102s 3ms/sample - loss: 0.8633 - dense_2_loss: 0.0108 - dense_3_loss: 0.0116 - dense_4_loss: 0.0102 - dense_5_loss: 0.0118 - dense_6_loss: 0.0102 - dense_7_loss: 0.0104 - dense_8_loss: 0.0112 - dense_9_loss: 0.0109 - dense_10_loss: 0.0123 - dense_11_loss: 0.0120 - dense_12_loss: 0.0095 - dense_13_loss: 0.0107 - dense_14_loss: 0.0093 - dense_15_loss: 0.0102 - dense_16_loss: 0.0112 - dense_17_loss: 0.0120 - dense_18_loss: 0.0122 - dense_19_loss: 0.0103 - dense_20_loss: 0.0097 - dense_21_loss: 0.0126 - dense_22_loss: 0.0091 - dense_23_loss: 0.0104 - dense_24_loss: 0.0108 - dense_25_loss: 0.0094 - dense_26_loss: 0.0105 - dense_27_loss: 0.0092 - dense_28_loss: 0.0120 - dense_29_loss: 0.0120 - dense_30_loss: 0.0096 - dense_31_loss: 0.0115 - dense_32_loss: 0.0116 - dense_33_loss: 0.0095 - dense_34_loss: 0.0117 - dense_35_loss: 0.0108 - dense_36_loss: 0.0099 - dense_37_loss: 0.0101 - dense_38_loss: 0.0094 - dense_39_loss: 0.0118 - dense_

Pass n° 4 ...
Train on 40000 samples, validate on 40000 samples
Epoch 1/4
40000/40000 [==============================] - 101s 3ms/sample - loss: 1.6084 - dense_2_loss: 0.0226 - dense_3_loss: 0.0198 - dense_4_loss: 0.0183 - dense_5_loss: 0.0211 - dense_6_loss: 0.0229 - dense_7_loss: 0.0183 - dense_8_loss: 0.0195 - dense_9_loss: 0.0188 - dense_10_loss: 0.0167 - dense_11_loss: 0.0225 - dense_12_loss: 0.0191 - dense_13_loss: 0.0207 - dense_14_loss: 0.0201 - dense_15_loss: 0.0208 - dense_16_loss: 0.0182 - dense_17_loss: 0.0186 - dense_18_loss: 0.0228 - dense_19_loss: 0.0223 - dense_20_loss: 0.0200 - dense_21_loss: 0.0170 - dense_22_loss: 0.0201 - dense_23_loss: 0.0182 - dense_24_loss: 0.0156 - dense_25_loss: 0.0181 - dense_26_loss: 0.0183 - dense_27_loss: 0.0186 - dense_28_loss: 0.0258 - dense_29_loss: 0.0213 - dense_30_loss: 0.0188 - dense_31_loss: 0.0220 - dense_32_loss: 0.0176 - dense_33_loss: 0.0189 - dense_34_loss: 0.0205 - dense_35_loss: 0.0178 - dense_36_loss: 0.0205 - dense_37_loss:

Epoch 2/4
40000/40000 [==============================] - 103s 3ms/sample - loss: 0.9678 - dense_2_loss: 0.0111 - dense_3_loss: 0.0127 - dense_4_loss: 0.0120 - dense_5_loss: 0.0123 - dense_6_loss: 0.0127 - dense_7_loss: 0.0104 - dense_8_loss: 0.0099 - dense_9_loss: 0.0109 - dense_10_loss: 0.0116 - dense_11_loss: 0.0110 - dense_12_loss: 0.0116 - dense_13_loss: 0.0133 - dense_14_loss: 0.0124 - dense_15_loss: 0.0113 - dense_16_loss: 0.0113 - dense_17_loss: 0.0118 - dense_18_loss: 0.0114 - dense_19_loss: 0.0127 - dense_20_loss: 0.0122 - dense_21_loss: 0.0117 - dense_22_loss: 0.0124 - dense_23_loss: 0.0108 - dense_24_loss: 0.0104 - dense_25_loss: 0.0117 - dense_26_loss: 0.0128 - dense_27_loss: 0.0139 - dense_28_loss: 0.0109 - dense_29_loss: 0.0124 - dense_30_loss: 0.0116 - dense_31_loss: 0.0134 - dense_32_loss: 0.0113 - dense_33_loss: 0.0104 - dense_34_loss: 0.0105 - dense_35_loss: 0.0127 - dense_36_loss: 0.0121 - dense_37_loss: 0.0118 - dense_38_loss: 0.0122 - dense_39_loss: 0.0109 - dense_

Epoch 3/4
40000/40000 [==============================] - 104s 3ms/sample - loss: 0.7782 - dense_2_loss: 0.0089 - dense_3_loss: 0.0089 - dense_4_loss: 0.0107 - dense_5_loss: 0.0081 - dense_6_loss: 0.0091 - dense_7_loss: 0.0090 - dense_8_loss: 0.0101 - dense_9_loss: 0.0090 - dense_10_loss: 0.0095 - dense_11_loss: 0.0098 - dense_12_loss: 0.0078 - dense_13_loss: 0.0087 - dense_14_loss: 0.0102 - dense_15_loss: 0.0104 - dense_16_loss: 0.0104 - dense_17_loss: 0.0093 - dense_18_loss: 0.0094 - dense_19_loss: 0.0110 - dense_20_loss: 0.0085 - dense_21_loss: 0.0086 - dense_22_loss: 0.0097 - dense_23_loss: 0.0093 - dense_24_loss: 0.0087 - dense_25_loss: 0.0104 - dense_26_loss: 0.0093 - dense_27_loss: 0.0102 - dense_28_loss: 0.0079 - dense_29_loss: 0.0087 - dense_30_loss: 0.0093 - dense_31_loss: 0.0097 - dense_32_loss: 0.0091 - dense_33_loss: 0.0083 - dense_34_loss: 0.0093 - dense_35_loss: 0.0113 - dense_36_loss: 0.0071 - dense_37_loss: 0.0101 - dense_38_loss: 0.0110 - dense_39_loss: 0.0084 - dense_

Epoch 4/4
40000/40000 [==============================] - 101s 3ms/sample - loss: 0.7034 - dense_2_loss: 0.0101 - dense_3_loss: 0.0082 - dense_4_loss: 0.0082 - dense_5_loss: 0.0077 - dense_6_loss: 0.0077 - dense_7_loss: 0.0083 - dense_8_loss: 0.0083 - dense_9_loss: 0.0101 - dense_10_loss: 0.0076 - dense_11_loss: 0.0090 - dense_12_loss: 0.0082 - dense_13_loss: 0.0103 - dense_14_loss: 0.0089 - dense_15_loss: 0.0107 - dense_16_loss: 0.0095 - dense_17_loss: 0.0072 - dense_18_loss: 0.0069 - dense_19_loss: 0.0090 - dense_20_loss: 0.0087 - dense_21_loss: 0.0080 - dense_22_loss: 0.0090 - dense_23_loss: 0.0087 - dense_24_loss: 0.0101 - dense_25_loss: 0.0100 - dense_26_loss: 0.0072 - dense_27_loss: 0.0078 - dense_28_loss: 0.0076 - dense_29_loss: 0.0083 - dense_30_loss: 0.0092 - dense_31_loss: 0.0085 - dense_32_loss: 0.0077 - dense_33_loss: 0.0072 - dense_34_loss: 0.0088 - dense_35_loss: 0.0088 - dense_36_loss: 0.0079 - dense_37_loss: 0.0093 - dense_38_loss: 0.0089 - dense_39_loss: 0.0068 - dense_

Pass n° 5 ...
Train on 40000 samples, validate on 40000 samples
Epoch 1/6
40000/40000 [==============================] - 104s 3ms/sample - loss: 1.8393 - dense_2_loss: 0.0211 - dense_3_loss: 0.0219 - dense_4_loss: 0.0232 - dense_5_loss: 0.0220 - dense_6_loss: 0.0241 - dense_7_loss: 0.0224 - dense_8_loss: 0.0220 - dense_9_loss: 0.0254 - dense_10_loss: 0.0223 - dense_11_loss: 0.0217 - dense_12_loss: 0.0243 - dense_13_loss: 0.0237 - dense_14_loss: 0.0233 - dense_15_loss: 0.0235 - dense_16_loss: 0.0217 - dense_17_loss: 0.0249 - dense_18_loss: 0.0245 - dense_19_loss: 0.0237 - dense_20_loss: 0.0223 - dense_21_loss: 0.0235 - dense_22_loss: 0.0227 - dense_23_loss: 0.0249 - dense_24_loss: 0.0227 - dense_25_loss: 0.0251 - dense_26_loss: 0.0214 - dense_27_loss: 0.0227 - dense_28_loss: 0.0228 - dense_29_loss: 0.0211 - dense_30_loss: 0.0236 - dense_31_loss: 0.0240 - dense_32_loss: 0.0236 - dense_33_loss: 0.0242 - dense_34_loss: 0.0216 - dense_35_loss: 0.0204 - dense_36_loss: 0.0226 - dense_37_loss:

Epoch 2/6
40000/40000 [==============================] - 106s 3ms/sample - loss: 1.0909 - dense_2_loss: 0.0127 - dense_3_loss: 0.0133 - dense_4_loss: 0.0154 - dense_5_loss: 0.0150 - dense_6_loss: 0.0136 - dense_7_loss: 0.0141 - dense_8_loss: 0.0146 - dense_9_loss: 0.0130 - dense_10_loss: 0.0126 - dense_11_loss: 0.0156 - dense_12_loss: 0.0145 - dense_13_loss: 0.0127 - dense_14_loss: 0.0140 - dense_15_loss: 0.0135 - dense_16_loss: 0.0134 - dense_17_loss: 0.0140 - dense_18_loss: 0.0128 - dense_19_loss: 0.0121 - dense_20_loss: 0.0129 - dense_21_loss: 0.0137 - dense_22_loss: 0.0137 - dense_23_loss: 0.0133 - dense_24_loss: 0.0137 - dense_25_loss: 0.0144 - dense_26_loss: 0.0128 - dense_27_loss: 0.0134 - dense_28_loss: 0.0134 - dense_29_loss: 0.0128 - dense_30_loss: 0.0144 - dense_31_loss: 0.0134 - dense_32_loss: 0.0137 - dense_33_loss: 0.0130 - dense_34_loss: 0.0136 - dense_35_loss: 0.0117 - dense_36_loss: 0.0127 - dense_37_loss: 0.0154 - dense_38_loss: 0.0127 - dense_39_loss: 0.0114 - dense_

Epoch 3/6
40000/40000 [==============================] - 113s 3ms/sample - loss: 0.8823 - dense_2_loss: 0.0106 - dense_3_loss: 0.0106 - dense_4_loss: 0.0123 - dense_5_loss: 0.0119 - dense_6_loss: 0.0096 - dense_7_loss: 0.0103 - dense_8_loss: 0.0104 - dense_9_loss: 0.0097 - dense_10_loss: 0.0100 - dense_11_loss: 0.0115 - dense_12_loss: 0.0101 - dense_13_loss: 0.0115 - dense_14_loss: 0.0102 - dense_15_loss: 0.0111 - dense_16_loss: 0.0109 - dense_17_loss: 0.0116 - dense_18_loss: 0.0095 - dense_19_loss: 0.0118 - dense_20_loss: 0.0117 - dense_21_loss: 0.0105 - dense_22_loss: 0.0106 - dense_23_loss: 0.0120 - dense_24_loss: 0.0116 - dense_25_loss: 0.0103 - dense_26_loss: 0.0108 - dense_27_loss: 0.0106 - dense_28_loss: 0.0121 - dense_29_loss: 0.0099 - dense_30_loss: 0.0120 - dense_31_loss: 0.0107 - dense_32_loss: 0.0106 - dense_33_loss: 0.0108 - dense_34_loss: 0.0101 - dense_35_loss: 0.0101 - dense_36_loss: 0.0134 - dense_37_loss: 0.0106 - dense_38_loss: 0.0115 - dense_39_loss: 0.0126 - dense_

Epoch 4/6
40000/40000 [==============================] - 106s 3ms/sample - loss: 0.7982 - dense_2_loss: 0.0093 - dense_3_loss: 0.0102 - dense_4_loss: 0.0098 - dense_5_loss: 0.0102 - dense_6_loss: 0.0117 - dense_7_loss: 0.0098 - dense_8_loss: 0.0091 - dense_9_loss: 0.0096 - dense_10_loss: 0.0087 - dense_11_loss: 0.0101 - dense_12_loss: 0.0089 - dense_13_loss: 0.0099 - dense_14_loss: 0.0103 - dense_15_loss: 0.0094 - dense_16_loss: 0.0102 - dense_17_loss: 0.0107 - dense_18_loss: 0.0107 - dense_19_loss: 0.0093 - dense_20_loss: 0.0093 - dense_21_loss: 0.0087 - dense_22_loss: 0.0099 - dense_23_loss: 0.0103 - dense_24_loss: 0.0104 - dense_25_loss: 0.0116 - dense_26_loss: 0.0107 - dense_27_loss: 0.0128 - dense_28_loss: 0.0109 - dense_29_loss: 0.0102 - dense_30_loss: 0.0112 - dense_31_loss: 0.0107 - dense_32_loss: 0.0087 - dense_33_loss: 0.0107 - dense_34_loss: 0.0080 - dense_35_loss: 0.0094 - dense_36_loss: 0.0103 - dense_37_loss: 0.0094 - dense_38_loss: 0.0095 - dense_39_loss: 0.0099 - dense_

Epoch 5/6
40000/40000 [==============================] - 103s 3ms/sample - loss: 0.7437 - dense_2_loss: 0.0107 - dense_3_loss: 0.0095 - dense_4_loss: 0.0091 - dense_5_loss: 0.0109 - dense_6_loss: 0.0101 - dense_7_loss: 0.0103 - dense_8_loss: 0.0079 - dense_9_loss: 0.0086 - dense_10_loss: 0.0091 - dense_11_loss: 0.0104 - dense_12_loss: 0.0094 - dense_13_loss: 0.0078 - dense_14_loss: 0.0100 - dense_15_loss: 0.0083 - dense_16_loss: 0.0096 - dense_17_loss: 0.0107 - dense_18_loss: 0.0110 - dense_19_loss: 0.0096 - dense_20_loss: 0.0113 - dense_21_loss: 0.0085 - dense_22_loss: 0.0087 - dense_23_loss: 0.0089 - dense_24_loss: 0.0109 - dense_25_loss: 0.0101 - dense_26_loss: 0.0103 - dense_27_loss: 0.0091 - dense_28_loss: 0.0082 - dense_29_loss: 0.0096 - dense_30_loss: 0.0101 - dense_31_loss: 0.0094 - dense_32_loss: 0.0080 - dense_33_loss: 0.0102 - dense_34_loss: 0.0083 - dense_35_loss: 0.0100 - dense_36_loss: 0.0081 - dense_37_loss: 0.0076 - dense_38_loss: 0.0106 - dense_39_loss: 0.0095 - dense_

Epoch 00005: early stopping
Pass n° 6 ...
Train on 40000 samples, validate on 40000 samples
Epoch 1/8
40000/40000 [==============================] - 104s 3ms/sample - loss: 1.9180 - dense_2_loss: 0.0264 - dense_3_loss: 0.0249 - dense_4_loss: 0.0234 - dense_5_loss: 0.0214 - dense_6_loss: 0.0238 - dense_7_loss: 0.0245 - dense_8_loss: 0.0227 - dense_9_loss: 0.0243 - dense_10_loss: 0.0250 - dense_11_loss: 0.0278 - dense_12_loss: 0.0220 - dense_13_loss: 0.0214 - dense_14_loss: 0.0232 - dense_15_loss: 0.0243 - dense_16_loss: 0.0218 - dense_17_loss: 0.0234 - dense_18_loss: 0.0218 - dense_19_loss: 0.0245 - dense_20_loss: 0.0244 - dense_21_loss: 0.0261 - dense_22_loss: 0.0216 - dense_23_loss: 0.0219 - dense_24_loss: 0.0228 - dense_25_loss: 0.0223 - dense_26_loss: 0.0260 - dense_27_loss: 0.0246 - dense_28_loss: 0.0244 - dense_29_loss: 0.0224 - dense_30_loss: 0.0232 - dense_31_loss: 0.0236 - dense_32_loss: 0.0243 - dense_33_loss: 0.0246 - dense_34_loss: 0.0266 - dense_35_loss: 0.0249 - dense_36_l

Epoch 2/8
40000/40000 [==============================] - 103s 3ms/sample - loss: 1.1612 - dense_2_loss: 0.0159 - dense_3_loss: 0.0158 - dense_4_loss: 0.0162 - dense_5_loss: 0.0150 - dense_6_loss: 0.0130 - dense_7_loss: 0.0144 - dense_8_loss: 0.0150 - dense_9_loss: 0.0141 - dense_10_loss: 0.0141 - dense_11_loss: 0.0148 - dense_12_loss: 0.0148 - dense_13_loss: 0.0141 - dense_14_loss: 0.0140 - dense_15_loss: 0.0128 - dense_16_loss: 0.0128 - dense_17_loss: 0.0138 - dense_18_loss: 0.0150 - dense_19_loss: 0.0136 - dense_20_loss: 0.0142 - dense_21_loss: 0.0155 - dense_22_loss: 0.0143 - dense_23_loss: 0.0126 - dense_24_loss: 0.0153 - dense_25_loss: 0.0164 - dense_26_loss: 0.0143 - dense_27_loss: 0.0135 - dense_28_loss: 0.0129 - dense_29_loss: 0.0160 - dense_30_loss: 0.0137 - dense_31_loss: 0.0134 - dense_32_loss: 0.0147 - dense_33_loss: 0.0144 - dense_34_loss: 0.0143 - dense_35_loss: 0.0134 - dense_36_loss: 0.0158 - dense_37_loss: 0.0143 - dense_38_loss: 0.0151 - dense_39_loss: 0.0141 - dense_

Epoch 3/8
40000/40000 [==============================] - 104s 3ms/sample - loss: 0.9650 - dense_2_loss: 0.0140 - dense_3_loss: 0.0109 - dense_4_loss: 0.0129 - dense_5_loss: 0.0116 - dense_6_loss: 0.0105 - dense_7_loss: 0.0119 - dense_8_loss: 0.0111 - dense_9_loss: 0.0134 - dense_10_loss: 0.0126 - dense_11_loss: 0.0128 - dense_12_loss: 0.0137 - dense_13_loss: 0.0126 - dense_14_loss: 0.0124 - dense_15_loss: 0.0114 - dense_16_loss: 0.0122 - dense_17_loss: 0.0127 - dense_18_loss: 0.0123 - dense_19_loss: 0.0126 - dense_20_loss: 0.0113 - dense_21_loss: 0.0120 - dense_22_loss: 0.0101 - dense_23_loss: 0.0120 - dense_24_loss: 0.0119 - dense_25_loss: 0.0119 - dense_26_loss: 0.0112 - dense_27_loss: 0.0117 - dense_28_loss: 0.0130 - dense_29_loss: 0.0114 - dense_30_loss: 0.0120 - dense_31_loss: 0.0121 - dense_32_loss: 0.0125 - dense_33_loss: 0.0124 - dense_34_loss: 0.0129 - dense_35_loss: 0.0115 - dense_36_loss: 0.0101 - dense_37_loss: 0.0104 - dense_38_loss: 0.0099 - dense_39_loss: 0.0117 - dense_

Epoch 4/8
40000/40000 [==============================] - 105s 3ms/sample - loss: 0.8709 - dense_2_loss: 0.0107 - dense_3_loss: 0.0103 - dense_4_loss: 0.0105 - dense_5_loss: 0.0112 - dense_6_loss: 0.0093 - dense_7_loss: 0.0100 - dense_8_loss: 0.0092 - dense_9_loss: 0.0110 - dense_10_loss: 0.0100 - dense_11_loss: 0.0123 - dense_12_loss: 0.0107 - dense_13_loss: 0.0126 - dense_14_loss: 0.0110 - dense_15_loss: 0.0103 - dense_16_loss: 0.0108 - dense_17_loss: 0.0097 - dense_18_loss: 0.0106 - dense_19_loss: 0.0103 - dense_20_loss: 0.0114 - dense_21_loss: 0.0104 - dense_22_loss: 0.0118 - dense_23_loss: 0.0102 - dense_24_loss: 0.0112 - dense_25_loss: 0.0110 - dense_26_loss: 0.0096 - dense_27_loss: 0.0111 - dense_28_loss: 0.0115 - dense_29_loss: 0.0106 - dense_30_loss: 0.0109 - dense_31_loss: 0.0109 - dense_32_loss: 0.0092 - dense_33_loss: 0.0096 - dense_34_loss: 0.0123 - dense_35_loss: 0.0120 - dense_36_loss: 0.0101 - dense_37_loss: 0.0110 - dense_38_loss: 0.0112 - dense_39_loss: 0.0110 - dense_

Epoch 5/8
40000/40000 [==============================] - 106s 3ms/sample - loss: 0.7905 - dense_2_loss: 0.0100 - dense_3_loss: 0.0098 - dense_4_loss: 0.0077 - dense_5_loss: 0.0106 - dense_6_loss: 0.0096 - dense_7_loss: 0.0084 - dense_8_loss: 0.0107 - dense_9_loss: 0.0096 - dense_10_loss: 0.0099 - dense_11_loss: 0.0104 - dense_12_loss: 0.0109 - dense_13_loss: 0.0097 - dense_14_loss: 0.0105 - dense_15_loss: 0.0101 - dense_16_loss: 0.0097 - dense_17_loss: 0.0096 - dense_18_loss: 0.0094 - dense_19_loss: 0.0104 - dense_20_loss: 0.0094 - dense_21_loss: 0.0105 - dense_22_loss: 0.0089 - dense_23_loss: 0.0083 - dense_24_loss: 0.0098 - dense_25_loss: 0.0104 - dense_26_loss: 0.0104 - dense_27_loss: 0.0093 - dense_28_loss: 0.0106 - dense_29_loss: 0.0085 - dense_30_loss: 0.0104 - dense_31_loss: 0.0085 - dense_32_loss: 0.0099 - dense_33_loss: 0.0099 - dense_34_loss: 0.0113 - dense_35_loss: 0.0101 - dense_36_loss: 0.0104 - dense_37_loss: 0.0093 - dense_38_loss: 0.0090 - dense_39_loss: 0.0093 - dense_

Epoch 00005: early stopping
Pass n° 7 ...
Train on 40000 samples, validate on 40000 samples
Epoch 1/10
40000/40000 [==============================] - 104s 3ms/sample - loss: 2.0807 - dense_2_loss: 0.0250 - dense_3_loss: 0.0295 - dense_4_loss: 0.0260 - dense_5_loss: 0.0271 - dense_6_loss: 0.0265 - dense_7_loss: 0.0271 - dense_8_loss: 0.0246 - dense_9_loss: 0.0261 - dense_10_loss: 0.0244 - dense_11_loss: 0.0232 - dense_12_loss: 0.0269 - dense_13_loss: 0.0249 - dense_14_loss: 0.0233 - dense_15_loss: 0.0274 - dense_16_loss: 0.0265 - dense_17_loss: 0.0249 - dense_18_loss: 0.0247 - dense_19_loss: 0.0265 - dense_20_loss: 0.0253 - dense_21_loss: 0.0264 - dense_22_loss: 0.0255 - dense_23_loss: 0.0280 - dense_24_loss: 0.0260 - dense_25_loss: 0.0229 - dense_26_loss: 0.0249 - dense_27_loss: 0.0262 - dense_28_loss: 0.0251 - dense_29_loss: 0.0256 - dense_30_loss: 0.0256 - dense_31_loss: 0.0277 - dense_32_loss: 0.0239 - dense_33_loss: 0.0249 - dense_34_loss: 0.0256 - dense_35_loss: 0.0245 - dense_36_

Epoch 2/10
40000/40000 [==============================] - 105s 3ms/sample - loss: 1.2574 - dense_2_loss: 0.0162 - dense_3_loss: 0.0163 - dense_4_loss: 0.0165 - dense_5_loss: 0.0150 - dense_6_loss: 0.0177 - dense_7_loss: 0.0145 - dense_8_loss: 0.0153 - dense_9_loss: 0.0143 - dense_10_loss: 0.0160 - dense_11_loss: 0.0146 - dense_12_loss: 0.0166 - dense_13_loss: 0.0157 - dense_14_loss: 0.0155 - dense_15_loss: 0.0163 - dense_16_loss: 0.0156 - dense_17_loss: 0.0145 - dense_18_loss: 0.0159 - dense_19_loss: 0.0132 - dense_20_loss: 0.0137 - dense_21_loss: 0.0154 - dense_22_loss: 0.0172 - dense_23_loss: 0.0142 - dense_24_loss: 0.0150 - dense_25_loss: 0.0135 - dense_26_loss: 0.0153 - dense_27_loss: 0.0148 - dense_28_loss: 0.0159 - dense_29_loss: 0.0166 - dense_30_loss: 0.0173 - dense_31_loss: 0.0161 - dense_32_loss: 0.0157 - dense_33_loss: 0.0139 - dense_34_loss: 0.0167 - dense_35_loss: 0.0161 - dense_36_loss: 0.0152 - dense_37_loss: 0.0157 - dense_38_loss: 0.0152 - dense_39_loss: 0.0147 - dense

Epoch 3/10
40000/40000 [==============================] - 104s 3ms/sample - loss: 1.0581 - dense_2_loss: 0.0124 - dense_3_loss: 0.0127 - dense_4_loss: 0.0128 - dense_5_loss: 0.0122 - dense_6_loss: 0.0146 - dense_7_loss: 0.0130 - dense_8_loss: 0.0129 - dense_9_loss: 0.0112 - dense_10_loss: 0.0132 - dense_11_loss: 0.0127 - dense_12_loss: 0.0128 - dense_13_loss: 0.0138 - dense_14_loss: 0.0112 - dense_15_loss: 0.0124 - dense_16_loss: 0.0126 - dense_17_loss: 0.0134 - dense_18_loss: 0.0138 - dense_19_loss: 0.0130 - dense_20_loss: 0.0122 - dense_21_loss: 0.0134 - dense_22_loss: 0.0129 - dense_23_loss: 0.0138 - dense_24_loss: 0.0139 - dense_25_loss: 0.0119 - dense_26_loss: 0.0142 - dense_27_loss: 0.0131 - dense_28_loss: 0.0127 - dense_29_loss: 0.0143 - dense_30_loss: 0.0128 - dense_31_loss: 0.0131 - dense_32_loss: 0.0146 - dense_33_loss: 0.0145 - dense_34_loss: 0.0123 - dense_35_loss: 0.0139 - dense_36_loss: 0.0134 - dense_37_loss: 0.0118 - dense_38_loss: 0.0132 - dense_39_loss: 0.0126 - dense

Epoch 4/10
40000/40000 [==============================] - 104s 3ms/sample - loss: 0.9477 - dense_2_loss: 0.0107 - dense_3_loss: 0.0135 - dense_4_loss: 0.0123 - dense_5_loss: 0.0111 - dense_6_loss: 0.0116 - dense_7_loss: 0.0111 - dense_8_loss: 0.0119 - dense_9_loss: 0.0102 - dense_10_loss: 0.0108 - dense_11_loss: 0.0123 - dense_12_loss: 0.0118 - dense_13_loss: 0.0127 - dense_14_loss: 0.0113 - dense_15_loss: 0.0121 - dense_16_loss: 0.0114 - dense_17_loss: 0.0107 - dense_18_loss: 0.0132 - dense_19_loss: 0.0114 - dense_20_loss: 0.0111 - dense_21_loss: 0.0118 - dense_22_loss: 0.0115 - dense_23_loss: 0.0112 - dense_24_loss: 0.0122 - dense_25_loss: 0.0108 - dense_26_loss: 0.0109 - dense_27_loss: 0.0114 - dense_28_loss: 0.0116 - dense_29_loss: 0.0123 - dense_30_loss: 0.0114 - dense_31_loss: 0.0133 - dense_32_loss: 0.0125 - dense_33_loss: 0.0103 - dense_34_loss: 0.0101 - dense_35_loss: 0.0114 - dense_36_loss: 0.0118 - dense_37_loss: 0.0124 - dense_38_loss: 0.0128 - dense_39_loss: 0.0116 - dense

Epoch 00004: early stopping
Pass n° 8 ...
Train on 40000 samples, validate on 40000 samples
Epoch 1/10
40000/40000 [==============================] - 105s 3ms/sample - loss: 2.3959 - dense_2_loss: 0.0310 - dense_3_loss: 0.0312 - dense_4_loss: 0.0292 - dense_5_loss: 0.0299 - dense_6_loss: 0.0306 - dense_7_loss: 0.0297 - dense_8_loss: 0.0327 - dense_9_loss: 0.0292 - dense_10_loss: 0.0292 - dense_11_loss: 0.0285 - dense_12_loss: 0.0307 - dense_13_loss: 0.0290 - dense_14_loss: 0.0276 - dense_15_loss: 0.0294 - dense_16_loss: 0.0296 - dense_17_loss: 0.0326 - dense_18_loss: 0.0305 - dense_19_loss: 0.0287 - dense_20_loss: 0.0307 - dense_21_loss: 0.0298 - dense_22_loss: 0.0297 - dense_23_loss: 0.0302 - dense_24_loss: 0.0275 - dense_25_loss: 0.0287 - dense_26_loss: 0.0293 - dense_27_loss: 0.0302 - dense_28_loss: 0.0303 - dense_29_loss: 0.0292 - dense_30_loss: 0.0286 - dense_31_loss: 0.0288 - dense_32_loss: 0.0288 - dense_33_loss: 0.0292 - dense_34_loss: 0.0296 - dense_35_loss: 0.0285 - dense_36_

Epoch 2/10
40000/40000 [==============================] - 106s 3ms/sample - loss: 1.4601 - dense_2_loss: 0.0191 - dense_3_loss: 0.0178 - dense_4_loss: 0.0195 - dense_5_loss: 0.0173 - dense_6_loss: 0.0166 - dense_7_loss: 0.0196 - dense_8_loss: 0.0181 - dense_9_loss: 0.0183 - dense_10_loss: 0.0193 - dense_11_loss: 0.0177 - dense_12_loss: 0.0171 - dense_13_loss: 0.0183 - dense_14_loss: 0.0176 - dense_15_loss: 0.0179 - dense_16_loss: 0.0177 - dense_17_loss: 0.0189 - dense_18_loss: 0.0167 - dense_19_loss: 0.0186 - dense_20_loss: 0.0186 - dense_21_loss: 0.0189 - dense_22_loss: 0.0182 - dense_23_loss: 0.0199 - dense_24_loss: 0.0190 - dense_25_loss: 0.0177 - dense_26_loss: 0.0166 - dense_27_loss: 0.0177 - dense_28_loss: 0.0167 - dense_29_loss: 0.0184 - dense_30_loss: 0.0155 - dense_31_loss: 0.0184 - dense_32_loss: 0.0184 - dense_33_loss: 0.0167 - dense_34_loss: 0.0158 - dense_35_loss: 0.0168 - dense_36_loss: 0.0168 - dense_37_loss: 0.0185 - dense_38_loss: 0.0179 - dense_39_loss: 0.0188 - dense

Epoch 3/10
40000/40000 [==============================] - 105s 3ms/sample - loss: 1.2348 - dense_2_loss: 0.0157 - dense_3_loss: 0.0143 - dense_4_loss: 0.0162 - dense_5_loss: 0.0161 - dense_6_loss: 0.0147 - dense_7_loss: 0.0159 - dense_8_loss: 0.0150 - dense_9_loss: 0.0156 - dense_10_loss: 0.0157 - dense_11_loss: 0.0149 - dense_12_loss: 0.0152 - dense_13_loss: 0.0176 - dense_14_loss: 0.0142 - dense_15_loss: 0.0164 - dense_16_loss: 0.0141 - dense_17_loss: 0.0158 - dense_18_loss: 0.0150 - dense_19_loss: 0.0151 - dense_20_loss: 0.0157 - dense_21_loss: 0.0158 - dense_22_loss: 0.0171 - dense_23_loss: 0.0136 - dense_24_loss: 0.0136 - dense_25_loss: 0.0137 - dense_26_loss: 0.0176 - dense_27_loss: 0.0147 - dense_28_loss: 0.0149 - dense_29_loss: 0.0140 - dense_30_loss: 0.0141 - dense_31_loss: 0.0151 - dense_32_loss: 0.0155 - dense_33_loss: 0.0151 - dense_34_loss: 0.0149 - dense_35_loss: 0.0142 - dense_36_loss: 0.0174 - dense_37_loss: 0.0146 - dense_38_loss: 0.0157 - dense_39_loss: 0.0144 - dense

Epoch 4/10
40000/40000 [==============================] - 105s 3ms/sample - loss: 1.1155 - dense_2_loss: 0.0147 - dense_3_loss: 0.0157 - dense_4_loss: 0.0142 - dense_5_loss: 0.0160 - dense_6_loss: 0.0140 - dense_7_loss: 0.0152 - dense_8_loss: 0.0131 - dense_9_loss: 0.0137 - dense_10_loss: 0.0140 - dense_11_loss: 0.0151 - dense_12_loss: 0.0126 - dense_13_loss: 0.0143 - dense_14_loss: 0.0136 - dense_15_loss: 0.0125 - dense_16_loss: 0.0123 - dense_17_loss: 0.0139 - dense_18_loss: 0.0132 - dense_19_loss: 0.0137 - dense_20_loss: 0.0142 - dense_21_loss: 0.0155 - dense_22_loss: 0.0141 - dense_23_loss: 0.0136 - dense_24_loss: 0.0143 - dense_25_loss: 0.0139 - dense_26_loss: 0.0137 - dense_27_loss: 0.0145 - dense_28_loss: 0.0153 - dense_29_loss: 0.0132 - dense_30_loss: 0.0136 - dense_31_loss: 0.0140 - dense_32_loss: 0.0143 - dense_33_loss: 0.0131 - dense_34_loss: 0.0137 - dense_35_loss: 0.0125 - dense_36_loss: 0.0143 - dense_37_loss: 0.0144 - dense_38_loss: 0.0143 - dense_39_loss: 0.0133 - dense

Epoch 00004: early stopping
Pass n° 9 ...
Train on 40000 samples, validate on 40000 samples
Epoch 1/10
40000/40000 [==============================] - 105s 3ms/sample - loss: 3.2319 - dense_2_loss: 0.0379 - dense_3_loss: 0.0380 - dense_4_loss: 0.0395 - dense_5_loss: 0.0435 - dense_6_loss: 0.0390 - dense_7_loss: 0.0361 - dense_8_loss: 0.0412 - dense_9_loss: 0.0391 - dense_10_loss: 0.0393 - dense_11_loss: 0.0384 - dense_12_loss: 0.0397 - dense_13_loss: 0.0402 - dense_14_loss: 0.0399 - dense_15_loss: 0.0399 - dense_16_loss: 0.0415 - dense_17_loss: 0.0426 - dense_18_loss: 0.0407 - dense_19_loss: 0.0398 - dense_20_loss: 0.0404 - dense_21_loss: 0.0398 - dense_22_loss: 0.0405 - dense_23_loss: 0.0400 - dense_24_loss: 0.0389 - dense_25_loss: 0.0418 - dense_26_loss: 0.0409 - dense_27_loss: 0.0393 - dense_28_loss: 0.0403 - dense_29_loss: 0.0388 - dense_30_loss: 0.0415 - dense_31_loss: 0.0401 - dense_32_loss: 0.0402 - dense_33_loss: 0.0409 - dense_34_loss: 0.0372 - dense_35_loss: 0.0409 - dense_36_

Epoch 2/10
40000/40000 [==============================] - 106s 3ms/sample - loss: 1.9954 - dense_2_loss: 0.0251 - dense_3_loss: 0.0245 - dense_4_loss: 0.0260 - dense_5_loss: 0.0227 - dense_6_loss: 0.0264 - dense_7_loss: 0.0244 - dense_8_loss: 0.0260 - dense_9_loss: 0.0230 - dense_10_loss: 0.0217 - dense_11_loss: 0.0275 - dense_12_loss: 0.0243 - dense_13_loss: 0.0265 - dense_14_loss: 0.0257 - dense_15_loss: 0.0251 - dense_16_loss: 0.0236 - dense_17_loss: 0.0240 - dense_18_loss: 0.0245 - dense_19_loss: 0.0231 - dense_20_loss: 0.0257 - dense_21_loss: 0.0243 - dense_22_loss: 0.0244 - dense_23_loss: 0.0254 - dense_24_loss: 0.0247 - dense_25_loss: 0.0248 - dense_26_loss: 0.0236 - dense_27_loss: 0.0245 - dense_28_loss: 0.0243 - dense_29_loss: 0.0229 - dense_30_loss: 0.0260 - dense_31_loss: 0.0234 - dense_32_loss: 0.0252 - dense_33_loss: 0.0262 - dense_34_loss: 0.0237 - dense_35_loss: 0.0253 - dense_36_loss: 0.0245 - dense_37_loss: 0.0248 - dense_38_loss: 0.0253 - dense_39_loss: 0.0238 - dense

Epoch 3/10
40000/40000 [==============================] - 108s 3ms/sample - loss: 1.6942 - dense_2_loss: 0.0200 - dense_3_loss: 0.0218 - dense_4_loss: 0.0216 - dense_5_loss: 0.0208 - dense_6_loss: 0.0193 - dense_7_loss: 0.0189 - dense_8_loss: 0.0221 - dense_9_loss: 0.0194 - dense_10_loss: 0.0210 - dense_11_loss: 0.0220 - dense_12_loss: 0.0195 - dense_13_loss: 0.0218 - dense_14_loss: 0.0211 - dense_15_loss: 0.0200 - dense_16_loss: 0.0215 - dense_17_loss: 0.0204 - dense_18_loss: 0.0199 - dense_19_loss: 0.0199 - dense_20_loss: 0.0220 - dense_21_loss: 0.0209 - dense_22_loss: 0.0185 - dense_23_loss: 0.0185 - dense_24_loss: 0.0210 - dense_25_loss: 0.0225 - dense_26_loss: 0.0223 - dense_27_loss: 0.0217 - dense_28_loss: 0.0198 - dense_29_loss: 0.0200 - dense_30_loss: 0.0220 - dense_31_loss: 0.0215 - dense_32_loss: 0.0223 - dense_33_loss: 0.0210 - dense_34_loss: 0.0208 - dense_35_loss: 0.0197 - dense_36_loss: 0.0208 - dense_37_loss: 0.0236 - dense_38_loss: 0.0223 - dense_39_loss: 0.0213 - dense

Epoch 00003: early stopping
Pass n° 10 ...
Train on 40000 samples, validate on 40000 samples
Epoch 1/10
40000/40000 [==============================] - 116s 3ms/sample - loss: 5.2609 - dense_2_loss: 0.0665 - dense_3_loss: 0.0665 - dense_4_loss: 0.0636 - dense_5_loss: 0.0643 - dense_6_loss: 0.0622 - dense_7_loss: 0.0620 - dense_8_loss: 0.0670 - dense_9_loss: 0.0662 - dense_10_loss: 0.0658 - dense_11_loss: 0.0677 - dense_12_loss: 0.0650 - dense_13_loss: 0.0644 - dense_14_loss: 0.0658 - dense_15_loss: 0.0667 - dense_16_loss: 0.0670 - dense_17_loss: 0.0635 - dense_18_loss: 0.0665 - dense_19_loss: 0.0644 - dense_20_loss: 0.0627 - dense_21_loss: 0.0639 - dense_22_loss: 0.0640 - dense_23_loss: 0.0663 - dense_24_loss: 0.0642 - dense_25_loss: 0.0644 - dense_26_loss: 0.0631 - dense_27_loss: 0.0644 - dense_28_loss: 0.0664 - dense_29_loss: 0.0643 - dense_30_loss: 0.0655 - dense_31_loss: 0.0631 - dense_32_loss: 0.0664 - dense_33_loss: 0.0640 - dense_34_loss: 0.0645 - dense_35_loss: 0.0664 - dense_36

Epoch 2/10
40000/40000 [==============================] - 116s 3ms/sample - loss: 3.5145 - dense_2_loss: 0.0434 - dense_3_loss: 0.0451 - dense_4_loss: 0.0402 - dense_5_loss: 0.0444 - dense_6_loss: 0.0449 - dense_7_loss: 0.0411 - dense_8_loss: 0.0463 - dense_9_loss: 0.0446 - dense_10_loss: 0.0416 - dense_11_loss: 0.0445 - dense_12_loss: 0.0444 - dense_13_loss: 0.0435 - dense_14_loss: 0.0443 - dense_15_loss: 0.0454 - dense_16_loss: 0.0456 - dense_17_loss: 0.0425 - dense_18_loss: 0.0450 - dense_19_loss: 0.0416 - dense_20_loss: 0.0422 - dense_21_loss: 0.0412 - dense_22_loss: 0.0425 - dense_23_loss: 0.0437 - dense_24_loss: 0.0419 - dense_25_loss: 0.0431 - dense_26_loss: 0.0432 - dense_27_loss: 0.0448 - dense_28_loss: 0.0436 - dense_29_loss: 0.0411 - dense_30_loss: 0.0418 - dense_31_loss: 0.0388 - dense_32_loss: 0.0466 - dense_33_loss: 0.0427 - dense_34_loss: 0.0441 - dense_35_loss: 0.0428 - dense_36_loss: 0.0449 - dense_37_loss: 0.0460 - dense_38_loss: 0.0422 - dense_39_loss: 0.0448 - dense

Epoch 3/10
40000/40000 [==============================] - 116s 3ms/sample - loss: 2.9840 - dense_2_loss: 0.0386 - dense_3_loss: 0.0379 - dense_4_loss: 0.0349 - dense_5_loss: 0.0397 - dense_6_loss: 0.0363 - dense_7_loss: 0.0351 - dense_8_loss: 0.0370 - dense_9_loss: 0.0389 - dense_10_loss: 0.0374 - dense_11_loss: 0.0360 - dense_12_loss: 0.0379 - dense_13_loss: 0.0366 - dense_14_loss: 0.0352 - dense_15_loss: 0.0389 - dense_16_loss: 0.0374 - dense_17_loss: 0.0372 - dense_18_loss: 0.0383 - dense_19_loss: 0.0355 - dense_20_loss: 0.0363 - dense_21_loss: 0.0338 - dense_22_loss: 0.0369 - dense_23_loss: 0.0355 - dense_24_loss: 0.0348 - dense_25_loss: 0.0375 - dense_26_loss: 0.0376 - dense_27_loss: 0.0361 - dense_28_loss: 0.0366 - dense_29_loss: 0.0350 - dense_30_loss: 0.0377 - dense_31_loss: 0.0353 - dense_32_loss: 0.0388 - dense_33_loss: 0.0361 - dense_34_loss: 0.0373 - dense_35_loss: 0.0379 - dense_36_loss: 0.0377 - dense_37_loss: 0.0369 - dense_38_loss: 0.0368 - dense_39_loss: 0.0368 - dense

Epoch 00003: early stopping
Pass n° 11 ...
Train on 40000 samples, validate on 40000 samples
Epoch 1/10
40000/40000 [==============================] - 125s 3ms/sample - loss: 7.7224 - dense_2_loss: 0.0957 - dense_3_loss: 0.0944 - dense_4_loss: 0.0958 - dense_5_loss: 0.0943 - dense_6_loss: 0.0949 - dense_7_loss: 0.0955 - dense_8_loss: 0.0991 - dense_9_loss: 0.0959 - dense_10_loss: 0.0963 - dense_11_loss: 0.0934 - dense_12_loss: 0.0978 - dense_13_loss: 0.0938 - dense_14_loss: 0.0919 - dense_15_loss: 0.0924 - dense_16_loss: 0.0946 - dense_17_loss: 0.0979 - dense_18_loss: 0.0939 - dense_19_loss: 0.0920 - dense_20_loss: 0.0916 - dense_21_loss: 0.0921 - dense_22_loss: 0.0980 - dense_23_loss: 0.0950 - dense_24_loss: 0.0982 - dense_25_loss: 0.0931 - dense_26_loss: 0.0973 - dense_27_loss: 0.0935 - dense_28_loss: 0.0976 - dense_29_loss: 0.0951 - dense_30_loss: 0.0935 - dense_31_loss: 0.0969 - dense_32_loss: 0.0937 - dense_33_loss: 0.0938 - dense_34_loss: 0.0965 - dense_35_loss: 0.0934 - dense_36

Epoch 2/10
40000/40000 [==============================] - 115s 3ms/sample - loss: 5.5921 - dense_2_loss: 0.0707 - dense_3_loss: 0.0699 - dense_4_loss: 0.0655 - dense_5_loss: 0.0704 - dense_6_loss: 0.0704 - dense_7_loss: 0.0693 - dense_8_loss: 0.0691 - dense_9_loss: 0.0691 - dense_10_loss: 0.0690 - dense_11_loss: 0.0693 - dense_12_loss: 0.0709 - dense_13_loss: 0.0700 - dense_14_loss: 0.0683 - dense_15_loss: 0.0681 - dense_16_loss: 0.0680 - dense_17_loss: 0.0713 - dense_18_loss: 0.0699 - dense_19_loss: 0.0665 - dense_20_loss: 0.0691 - dense_21_loss: 0.0655 - dense_22_loss: 0.0695 - dense_23_loss: 0.0701 - dense_24_loss: 0.0718 - dense_25_loss: 0.0669 - dense_26_loss: 0.0700 - dense_27_loss: 0.0669 - dense_28_loss: 0.0701 - dense_29_loss: 0.0674 - dense_30_loss: 0.0684 - dense_31_loss: 0.0682 - dense_32_loss: 0.0670 - dense_33_loss: 0.0688 - dense_34_loss: 0.0696 - dense_35_loss: 0.0699 - dense_36_loss: 0.0718 - dense_37_loss: 0.0721 - dense_38_loss: 0.0700 - dense_39_loss: 0.0729 - dense

Epoch 3/10
40000/40000 [==============================] - 111s 3ms/sample - loss: 4.8396 - dense_2_loss: 0.0575 - dense_3_loss: 0.0610 - dense_4_loss: 0.0582 - dense_5_loss: 0.0615 - dense_6_loss: 0.0618 - dense_7_loss: 0.0573 - dense_8_loss: 0.0624 - dense_9_loss: 0.0605 - dense_10_loss: 0.0601 - dense_11_loss: 0.0597 - dense_12_loss: 0.0607 - dense_13_loss: 0.0594 - dense_14_loss: 0.0556 - dense_15_loss: 0.0594 - dense_16_loss: 0.0582 - dense_17_loss: 0.0619 - dense_18_loss: 0.0592 - dense_19_loss: 0.0574 - dense_20_loss: 0.0607 - dense_21_loss: 0.0586 - dense_22_loss: 0.0590 - dense_23_loss: 0.0606 - dense_24_loss: 0.0612 - dense_25_loss: 0.0584 - dense_26_loss: 0.0594 - dense_27_loss: 0.0607 - dense_28_loss: 0.0601 - dense_29_loss: 0.0593 - dense_30_loss: 0.0600 - dense_31_loss: 0.0571 - dense_32_loss: 0.0565 - dense_33_loss: 0.0573 - dense_34_loss: 0.0609 - dense_35_loss: 0.0596 - dense_36_loss: 0.0623 - dense_37_loss: 0.0605 - dense_38_loss: 0.0600 - dense_39_loss: 0.0611 - dense

Epoch 00003: early stopping
Pass n° 12 ...
Train on 40000 samples, validate on 40000 samples
Epoch 1/10
40000/40000 [==============================] - 111s 3ms/sample - loss: 10.6348 - dense_2_loss: 0.1344 - dense_3_loss: 0.1330 - dense_4_loss: 0.1284 - dense_5_loss: 0.1287 - dense_6_loss: 0.1305 - dense_7_loss: 0.1328 - dense_8_loss: 0.1331 - dense_9_loss: 0.1299 - dense_10_loss: 0.1343 - dense_11_loss: 0.1314 - dense_12_loss: 0.1328 - dense_13_loss: 0.1299 - dense_14_loss: 0.1297 - dense_15_loss: 0.1310 - dense_16_loss: 0.1288 - dense_17_loss: 0.1339 - dense_18_loss: 0.1343 - dense_19_loss: 0.1304 - dense_20_loss: 0.1319 - dense_21_loss: 0.1328 - dense_22_loss: 0.1307 - dense_23_loss: 0.1313 - dense_24_loss: 0.1332 - dense_25_loss: 0.1301 - dense_26_loss: 0.1274 - dense_27_loss: 0.1314 - dense_28_loss: 0.1283 - dense_29_loss: 0.1348 - dense_30_loss: 0.1344 - dense_31_loss: 0.1317 - dense_32_loss: 0.1321 - dense_33_loss: 0.1312 - dense_34_loss: 0.1322 - dense_35_loss: 0.1299 - dense_3

Epoch 2/10
40000/40000 [==============================] - 112s 3ms/sample - loss: 8.2417 - dense_2_loss: 0.1021 - dense_3_loss: 0.1068 - dense_4_loss: 0.0984 - dense_5_loss: 0.0995 - dense_6_loss: 0.1023 - dense_7_loss: 0.0992 - dense_8_loss: 0.1041 - dense_9_loss: 0.0986 - dense_10_loss: 0.1056 - dense_11_loss: 0.1015 - dense_12_loss: 0.1055 - dense_13_loss: 0.1009 - dense_14_loss: 0.1006 - dense_15_loss: 0.1013 - dense_16_loss: 0.0990 - dense_17_loss: 0.0999 - dense_18_loss: 0.1049 - dense_19_loss: 0.1030 - dense_20_loss: 0.1055 - dense_21_loss: 0.1028 - dense_22_loss: 0.1010 - dense_23_loss: 0.1027 - dense_24_loss: 0.1009 - dense_25_loss: 0.1012 - dense_26_loss: 0.0990 - dense_27_loss: 0.1006 - dense_28_loss: 0.0996 - dense_29_loss: 0.1027 - dense_30_loss: 0.1026 - dense_31_loss: 0.1015 - dense_32_loss: 0.1010 - dense_33_loss: 0.1023 - dense_34_loss: 0.1000 - dense_35_loss: 0.1020 - dense_36_loss: 0.1002 - dense_37_loss: 0.1037 - dense_38_loss: 0.1026 - dense_39_loss: 0.0996 - dense

Epoch 3/10
40000/40000 [==============================] - 113s 3ms/sample - loss: 7.3070 - dense_2_loss: 0.0930 - dense_3_loss: 0.0941 - dense_4_loss: 0.0871 - dense_5_loss: 0.0867 - dense_6_loss: 0.0896 - dense_7_loss: 0.0901 - dense_8_loss: 0.0897 - dense_9_loss: 0.0901 - dense_10_loss: 0.0942 - dense_11_loss: 0.0886 - dense_12_loss: 0.0924 - dense_13_loss: 0.0900 - dense_14_loss: 0.0904 - dense_15_loss: 0.0913 - dense_16_loss: 0.0882 - dense_17_loss: 0.0890 - dense_18_loss: 0.0924 - dense_19_loss: 0.0861 - dense_20_loss: 0.0903 - dense_21_loss: 0.0898 - dense_22_loss: 0.0909 - dense_23_loss: 0.0916 - dense_24_loss: 0.0883 - dense_25_loss: 0.0883 - dense_26_loss: 0.0854 - dense_27_loss: 0.0873 - dense_28_loss: 0.0887 - dense_29_loss: 0.0910 - dense_30_loss: 0.0927 - dense_31_loss: 0.0904 - dense_32_loss: 0.0908 - dense_33_loss: 0.0855 - dense_34_loss: 0.0911 - dense_35_loss: 0.0915 - dense_36_loss: 0.0880 - dense_37_loss: 0.0893 - dense_38_loss: 0.0910 - dense_39_loss: 0.0863 - dense

Epoch 00003: early stopping
Pass n° 13 ...
Train on 40000 samples, validate on 40000 samples
Epoch 1/10
40000/40000 [==============================] - 114s 3ms/sample - loss: 14.0431 - dense_2_loss: 0.1779 - dense_3_loss: 0.1746 - dense_4_loss: 0.1741 - dense_5_loss: 0.1721 - dense_6_loss: 0.1706 - dense_7_loss: 0.1732 - dense_8_loss: 0.1737 - dense_9_loss: 0.1724 - dense_10_loss: 0.1716 - dense_11_loss: 0.1752 - dense_12_loss: 0.1734 - dense_13_loss: 0.1733 - dense_14_loss: 0.1755 - dense_15_loss: 0.1720 - dense_16_loss: 0.1764 - dense_17_loss: 0.1782 - dense_18_loss: 0.1699 - dense_19_loss: 0.1724 - dense_20_loss: 0.1746 - dense_21_loss: 0.1739 - dense_22_loss: 0.1770 - dense_23_loss: 0.1741 - dense_24_loss: 0.1715 - dense_25_loss: 0.1736 - dense_26_loss: 0.1740 - dense_27_loss: 0.1704 - dense_28_loss: 0.1774 - dense_29_loss: 0.1743 - dense_30_loss: 0.1716 - dense_31_loss: 0.1688 - dense_32_loss: 0.1740 - dense_33_loss: 0.1718 - dense_34_loss: 0.1757 - dense_35_loss: 0.1789 - dense_3

Epoch 2/10
40000/40000 [==============================] - 114s 3ms/sample - loss: 11.4417 - dense_2_loss: 0.1446 - dense_3_loss: 0.1444 - dense_4_loss: 0.1419 - dense_5_loss: 0.1415 - dense_6_loss: 0.1400 - dense_7_loss: 0.1392 - dense_8_loss: 0.1405 - dense_9_loss: 0.1391 - dense_10_loss: 0.1402 - dense_11_loss: 0.1430 - dense_12_loss: 0.1425 - dense_13_loss: 0.1399 - dense_14_loss: 0.1445 - dense_15_loss: 0.1417 - dense_16_loss: 0.1450 - dense_17_loss: 0.1441 - dense_18_loss: 0.1381 - dense_19_loss: 0.1428 - dense_20_loss: 0.1409 - dense_21_loss: 0.1456 - dense_22_loss: 0.1424 - dense_23_loss: 0.1452 - dense_24_loss: 0.1420 - dense_25_loss: 0.1434 - dense_26_loss: 0.1448 - dense_27_loss: 0.1393 - dense_28_loss: 0.1449 - dense_29_loss: 0.1429 - dense_30_loss: 0.1362 - dense_31_loss: 0.1361 - dense_32_loss: 0.1384 - dense_33_loss: 0.1402 - dense_34_loss: 0.1447 - dense_35_loss: 0.1460 - dense_36_loss: 0.1399 - dense_37_loss: 0.1426 - dense_38_loss: 0.1427 - dense_39_loss: 0.1448 - dens

Epoch 3/10
40000/40000 [==============================] - 114s 3ms/sample - loss: 10.4200 - dense_2_loss: 0.1325 - dense_3_loss: 0.1277 - dense_4_loss: 0.1316 - dense_5_loss: 0.1277 - dense_6_loss: 0.1266 - dense_7_loss: 0.1258 - dense_8_loss: 0.1260 - dense_9_loss: 0.1277 - dense_10_loss: 0.1269 - dense_11_loss: 0.1291 - dense_12_loss: 0.1282 - dense_13_loss: 0.1309 - dense_14_loss: 0.1307 - dense_15_loss: 0.1272 - dense_16_loss: 0.1321 - dense_17_loss: 0.1274 - dense_18_loss: 0.1255 - dense_19_loss: 0.1276 - dense_20_loss: 0.1298 - dense_21_loss: 0.1318 - dense_22_loss: 0.1270 - dense_23_loss: 0.1323 - dense_24_loss: 0.1288 - dense_25_loss: 0.1300 - dense_26_loss: 0.1316 - dense_27_loss: 0.1279 - dense_28_loss: 0.1300 - dense_29_loss: 0.1295 - dense_30_loss: 0.1269 - dense_31_loss: 0.1248 - dense_32_loss: 0.1273 - dense_33_loss: 0.1246 - dense_34_loss: 0.1317 - dense_35_loss: 0.1335 - dense_36_loss: 0.1284 - dense_37_loss: 0.1307 - dense_38_loss: 0.1324 - dense_39_loss: 0.1280 - dens

Epoch 00003: early stopping
Pass n° 14 ...
Train on 40000 samples, validate on 40000 samples
Epoch 1/10
40000/40000 [==============================] - 115s 3ms/sample - loss: 17.9420 - dense_2_loss: 0.2201 - dense_3_loss: 0.2198 - dense_4_loss: 0.2198 - dense_5_loss: 0.2202 - dense_6_loss: 0.2162 - dense_7_loss: 0.2212 - dense_8_loss: 0.2191 - dense_9_loss: 0.2203 - dense_10_loss: 0.2238 - dense_11_loss: 0.2221 - dense_12_loss: 0.2244 - dense_13_loss: 0.2209 - dense_14_loss: 0.2194 - dense_15_loss: 0.2232 - dense_16_loss: 0.2193 - dense_17_loss: 0.2222 - dense_18_loss: 0.2205 - dense_19_loss: 0.2199 - dense_20_loss: 0.2189 - dense_21_loss: 0.2218 - dense_22_loss: 0.2209 - dense_23_loss: 0.2208 - dense_24_loss: 0.2249 - dense_25_loss: 0.2229 - dense_26_loss: 0.2190 - dense_27_loss: 0.2203 - dense_28_loss: 0.2194 - dense_29_loss: 0.2250 - dense_30_loss: 0.2212 - dense_31_loss: 0.2190 - dense_32_loss: 0.2198 - dense_33_loss: 0.2261 - dense_34_loss: 0.2246 - dense_35_loss: 0.2183 - dense_3

Epoch 2/10
40000/40000 [==============================] - 115s 3ms/sample - loss: 15.1987 - dense_2_loss: 0.1914 - dense_3_loss: 0.1873 - dense_4_loss: 0.1848 - dense_5_loss: 0.1851 - dense_6_loss: 0.1853 - dense_7_loss: 0.1866 - dense_8_loss: 0.1836 - dense_9_loss: 0.1841 - dense_10_loss: 0.1886 - dense_11_loss: 0.1848 - dense_12_loss: 0.1877 - dense_13_loss: 0.1878 - dense_14_loss: 0.1883 - dense_15_loss: 0.1914 - dense_16_loss: 0.1855 - dense_17_loss: 0.1865 - dense_18_loss: 0.1833 - dense_19_loss: 0.1870 - dense_20_loss: 0.1885 - dense_21_loss: 0.1835 - dense_22_loss: 0.1875 - dense_23_loss: 0.1904 - dense_24_loss: 0.1919 - dense_25_loss: 0.1896 - dense_26_loss: 0.1869 - dense_27_loss: 0.1922 - dense_28_loss: 0.1869 - dense_29_loss: 0.1895 - dense_30_loss: 0.1906 - dense_31_loss: 0.1842 - dense_32_loss: 0.1877 - dense_33_loss: 0.1909 - dense_34_loss: 0.1886 - dense_35_loss: 0.1856 - dense_36_loss: 0.1852 - dense_37_loss: 0.1927 - dense_38_loss: 0.1905 - dense_39_loss: 0.1899 - dens

Epoch 3/10
40000/40000 [==============================] - 116s 3ms/sample - loss: 14.1144 - dense_2_loss: 0.1734 - dense_3_loss: 0.1742 - dense_4_loss: 0.1726 - dense_5_loss: 0.1698 - dense_6_loss: 0.1732 - dense_7_loss: 0.1751 - dense_8_loss: 0.1700 - dense_9_loss: 0.1727 - dense_10_loss: 0.1757 - dense_11_loss: 0.1739 - dense_12_loss: 0.1769 - dense_13_loss: 0.1737 - dense_14_loss: 0.1726 - dense_15_loss: 0.1756 - dense_16_loss: 0.1728 - dense_17_loss: 0.1719 - dense_18_loss: 0.1706 - dense_19_loss: 0.1754 - dense_20_loss: 0.1768 - dense_21_loss: 0.1740 - dense_22_loss: 0.1736 - dense_23_loss: 0.1789 - dense_24_loss: 0.1741 - dense_25_loss: 0.1754 - dense_26_loss: 0.1733 - dense_27_loss: 0.1751 - dense_28_loss: 0.1716 - dense_29_loss: 0.1753 - dense_30_loss: 0.1780 - dense_31_loss: 0.1712 - dense_32_loss: 0.1746 - dense_33_loss: 0.1766 - dense_34_loss: 0.1758 - dense_35_loss: 0.1721 - dense_36_loss: 0.1732 - dense_37_loss: 0.1794 - dense_38_loss: 0.1750 - dense_39_loss: 0.1751 - dens

Epoch 00003: early stopping
Pass n° 15 ...
Train on 40000 samples, validate on 40000 samples
Epoch 1/10
40000/40000 [==============================] - 116s 3ms/sample - loss: 22.1426 - dense_2_loss: 0.2668 - dense_3_loss: 0.2730 - dense_4_loss: 0.2742 - dense_5_loss: 0.2729 - dense_6_loss: 0.2709 - dense_7_loss: 0.2744 - dense_8_loss: 0.2741 - dense_9_loss: 0.2705 - dense_10_loss: 0.2736 - dense_11_loss: 0.2708 - dense_12_loss: 0.2718 - dense_13_loss: 0.2704 - dense_14_loss: 0.2739 - dense_15_loss: 0.2728 - dense_16_loss: 0.2729 - dense_17_loss: 0.2743 - dense_18_loss: 0.2700 - dense_19_loss: 0.2714 - dense_20_loss: 0.2734 - dense_21_loss: 0.2716 - dense_22_loss: 0.2698 - dense_23_loss: 0.2720 - dense_24_loss: 0.2737 - dense_25_loss: 0.2711 - dense_26_loss: 0.2735 - dense_27_loss: 0.2702 - dense_28_loss: 0.2755 - dense_29_loss: 0.2733 - dense_30_loss: 0.2777 - dense_31_loss: 0.2761 - dense_32_loss: 0.2762 - dense_33_loss: 0.2737 - dense_34_loss: 0.2737 - dense_35_loss: 0.2715 - dense_3

Epoch 2/10
40000/40000 [==============================] - 117s 3ms/sample - loss: 19.4026 - dense_2_loss: 0.2347 - dense_3_loss: 0.2392 - dense_4_loss: 0.2355 - dense_5_loss: 0.2387 - dense_6_loss: 0.2356 - dense_7_loss: 0.2445 - dense_8_loss: 0.2419 - dense_9_loss: 0.2364 - dense_10_loss: 0.2388 - dense_11_loss: 0.2367 - dense_12_loss: 0.2390 - dense_13_loss: 0.2370 - dense_14_loss: 0.2393 - dense_15_loss: 0.2382 - dense_16_loss: 0.2385 - dense_17_loss: 0.2397 - dense_18_loss: 0.2349 - dense_19_loss: 0.2379 - dense_20_loss: 0.2397 - dense_21_loss: 0.2370 - dense_22_loss: 0.2391 - dense_23_loss: 0.2401 - dense_24_loss: 0.2417 - dense_25_loss: 0.2361 - dense_26_loss: 0.2414 - dense_27_loss: 0.2377 - dense_28_loss: 0.2398 - dense_29_loss: 0.2397 - dense_30_loss: 0.2424 - dense_31_loss: 0.2448 - dense_32_loss: 0.2431 - dense_33_loss: 0.2424 - dense_34_loss: 0.2400 - dense_35_loss: 0.2392 - dense_36_loss: 0.2361 - dense_37_loss: 0.2410 - dense_38_loss: 0.2443 - dense_39_loss: 0.2387 - dens

Epoch 3/10
40000/40000 [==============================] - 117s 3ms/sample - loss: 18.2704 - dense_2_loss: 0.2219 - dense_3_loss: 0.2248 - dense_4_loss: 0.2250 - dense_5_loss: 0.2226 - dense_6_loss: 0.2226 - dense_7_loss: 0.2259 - dense_8_loss: 0.2269 - dense_9_loss: 0.2227 - dense_10_loss: 0.2295 - dense_11_loss: 0.2235 - dense_12_loss: 0.2268 - dense_13_loss: 0.2231 - dense_14_loss: 0.2245 - dense_15_loss: 0.2260 - dense_16_loss: 0.2230 - dense_17_loss: 0.2270 - dense_18_loss: 0.2225 - dense_19_loss: 0.2228 - dense_20_loss: 0.2242 - dense_21_loss: 0.2215 - dense_22_loss: 0.2213 - dense_23_loss: 0.2228 - dense_24_loss: 0.2262 - dense_25_loss: 0.2262 - dense_26_loss: 0.2246 - dense_27_loss: 0.2221 - dense_28_loss: 0.2250 - dense_29_loss: 0.2266 - dense_30_loss: 0.2311 - dense_31_loss: 0.2290 - dense_32_loss: 0.2271 - dense_33_loss: 0.2292 - dense_34_loss: 0.2262 - dense_35_loss: 0.2264 - dense_36_loss: 0.2257 - dense_37_loss: 0.2272 - dense_38_loss: 0.2292 - dense_39_loss: 0.2238 - dens

Epoch 00003: early stopping
Pass n° 16 ...
Train on 40000 samples, validate on 40000 samples
Epoch 1/10
40000/40000 [==============================] - 118s 3ms/sample - loss: 26.8575 - dense_2_loss: 0.3317 - dense_3_loss: 0.3337 - dense_4_loss: 0.3256 - dense_5_loss: 0.3303 - dense_6_loss: 0.3331 - dense_7_loss: 0.3307 - dense_8_loss: 0.3307 - dense_9_loss: 0.3307 - dense_10_loss: 0.3284 - dense_11_loss: 0.3324 - dense_12_loss: 0.3314 - dense_13_loss: 0.3354 - dense_14_loss: 0.3301 - dense_15_loss: 0.3324 - dense_16_loss: 0.3360 - dense_17_loss: 0.3291 - dense_18_loss: 0.3282 - dense_19_loss: 0.3358 - dense_20_loss: 0.3344 - dense_21_loss: 0.3323 - dense_22_loss: 0.3231 - dense_23_loss: 0.3272 - dense_24_loss: 0.3306 - dense_25_loss: 0.3323 - dense_26_loss: 0.3327 - dense_27_loss: 0.3308 - dense_28_loss: 0.3321 - dense_29_loss: 0.3347 - dense_30_loss: 0.3320 - dense_31_loss: 0.3294 - dense_32_loss: 0.3314 - dense_33_loss: 0.3289 - dense_34_loss: 0.3332 - dense_35_loss: 0.3282 - dense_3

Epoch 2/10
40000/40000 [==============================] - 118s 3ms/sample - loss: 24.1094 - dense_2_loss: 0.2972 - dense_3_loss: 0.3003 - dense_4_loss: 0.2912 - dense_5_loss: 0.2925 - dense_6_loss: 0.2978 - dense_7_loss: 0.2965 - dense_8_loss: 0.2965 - dense_9_loss: 0.2947 - dense_10_loss: 0.2957 - dense_11_loss: 0.2990 - dense_12_loss: 0.3011 - dense_13_loss: 0.2979 - dense_14_loss: 0.2942 - dense_15_loss: 0.2989 - dense_16_loss: 0.3007 - dense_17_loss: 0.2958 - dense_18_loss: 0.2929 - dense_19_loss: 0.2965 - dense_20_loss: 0.2985 - dense_21_loss: 0.3009 - dense_22_loss: 0.2864 - dense_23_loss: 0.2934 - dense_24_loss: 0.2950 - dense_25_loss: 0.2963 - dense_26_loss: 0.2993 - dense_27_loss: 0.3002 - dense_28_loss: 0.2963 - dense_29_loss: 0.3002 - dense_30_loss: 0.2991 - dense_31_loss: 0.2948 - dense_32_loss: 0.2977 - dense_33_loss: 0.2979 - dense_34_loss: 0.3006 - dense_35_loss: 0.2928 - dense_36_loss: 0.3007 - dense_37_loss: 0.2968 - dense_38_loss: 0.3043 - dense_39_loss: 0.2975 - dens

Epoch 3/10
40000/40000 [==============================] - 120s 3ms/sample - loss: 22.9293 - dense_2_loss: 0.2840 - dense_3_loss: 0.2859 - dense_4_loss: 0.2767 - dense_5_loss: 0.2802 - dense_6_loss: 0.2831 - dense_7_loss: 0.2811 - dense_8_loss: 0.2819 - dense_9_loss: 0.2808 - dense_10_loss: 0.2845 - dense_11_loss: 0.2818 - dense_12_loss: 0.2874 - dense_13_loss: 0.2865 - dense_14_loss: 0.2821 - dense_15_loss: 0.2840 - dense_16_loss: 0.2854 - dense_17_loss: 0.2810 - dense_18_loss: 0.2780 - dense_19_loss: 0.2860 - dense_20_loss: 0.2848 - dense_21_loss: 0.2859 - dense_22_loss: 0.2728 - dense_23_loss: 0.2777 - dense_24_loss: 0.2798 - dense_25_loss: 0.2857 - dense_26_loss: 0.2835 - dense_27_loss: 0.2859 - dense_28_loss: 0.2829 - dense_29_loss: 0.2842 - dense_30_loss: 0.2847 - dense_31_loss: 0.2786 - dense_32_loss: 0.2850 - dense_33_loss: 0.2815 - dense_34_loss: 0.2856 - dense_35_loss: 0.2815 - dense_36_loss: 0.2827 - dense_37_loss: 0.2825 - dense_38_loss: 0.2862 - dense_39_loss: 0.2852 - dens

Epoch 00003: early stopping
Pass n° 17 ...
Train on 40000 samples, validate on 40000 samples
Epoch 1/10
40000/40000 [==============================] - 119s 3ms/sample - loss: 31.8436 - dense_2_loss: 0.3895 - dense_3_loss: 0.3924 - dense_4_loss: 0.3874 - dense_5_loss: 0.3910 - dense_6_loss: 0.3907 - dense_7_loss: 0.3928 - dense_8_loss: 0.3929 - dense_9_loss: 0.3914 - dense_10_loss: 0.3919 - dense_11_loss: 0.3939 - dense_12_loss: 0.3953 - dense_13_loss: 0.3935 - dense_14_loss: 0.3923 - dense_15_loss: 0.3913 - dense_16_loss: 0.3936 - dense_17_loss: 0.3885 - dense_18_loss: 0.3964 - dense_19_loss: 0.3987 - dense_20_loss: 0.3952 - dense_21_loss: 0.3899 - dense_22_loss: 0.3902 - dense_23_loss: 0.3906 - dense_24_loss: 0.3929 - dense_25_loss: 0.3890 - dense_26_loss: 0.3927 - dense_27_loss: 0.3950 - dense_28_loss: 0.3871 - dense_29_loss: 0.3948 - dense_30_loss: 0.3912 - dense_31_loss: 0.3927 - dense_32_loss: 0.4007 - dense_33_loss: 0.3962 - dense_34_loss: 0.3925 - dense_35_loss: 0.3949 - dense_3

Epoch 2/10
40000/40000 [==============================] - 120s 3ms/sample - loss: 29.1327 - dense_2_loss: 0.3575 - dense_3_loss: 0.3607 - dense_4_loss: 0.3556 - dense_5_loss: 0.3583 - dense_6_loss: 0.3587 - dense_7_loss: 0.3610 - dense_8_loss: 0.3621 - dense_9_loss: 0.3581 - dense_10_loss: 0.3568 - dense_11_loss: 0.3602 - dense_12_loss: 0.3606 - dense_13_loss: 0.3611 - dense_14_loss: 0.3603 - dense_15_loss: 0.3554 - dense_16_loss: 0.3598 - dense_17_loss: 0.3552 - dense_18_loss: 0.3608 - dense_19_loss: 0.3651 - dense_20_loss: 0.3605 - dense_21_loss: 0.3543 - dense_22_loss: 0.3567 - dense_23_loss: 0.3560 - dense_24_loss: 0.3571 - dense_25_loss: 0.3572 - dense_26_loss: 0.3601 - dense_27_loss: 0.3607 - dense_28_loss: 0.3533 - dense_29_loss: 0.3593 - dense_30_loss: 0.3575 - dense_31_loss: 0.3616 - dense_32_loss: 0.3675 - dense_33_loss: 0.3600 - dense_34_loss: 0.3615 - dense_35_loss: 0.3614 - dense_36_loss: 0.3627 - dense_37_loss: 0.3650 - dense_38_loss: 0.3643 - dense_39_loss: 0.3593 - dens

Epoch 3/10
40000/40000 [==============================] - 120s 3ms/sample - loss: 27.9411 - dense_2_loss: 0.3452 - dense_3_loss: 0.3479 - dense_4_loss: 0.3400 - dense_5_loss: 0.3428 - dense_6_loss: 0.3432 - dense_7_loss: 0.3442 - dense_8_loss: 0.3490 - dense_9_loss: 0.3437 - dense_10_loss: 0.3438 - dense_11_loss: 0.3460 - dense_12_loss: 0.3455 - dense_13_loss: 0.3435 - dense_14_loss: 0.3472 - dense_15_loss: 0.3456 - dense_16_loss: 0.3452 - dense_17_loss: 0.3403 - dense_18_loss: 0.3468 - dense_19_loss: 0.3474 - dense_20_loss: 0.3465 - dense_21_loss: 0.3387 - dense_22_loss: 0.3443 - dense_23_loss: 0.3428 - dense_24_loss: 0.3410 - dense_25_loss: 0.3400 - dense_26_loss: 0.3440 - dense_27_loss: 0.3440 - dense_28_loss: 0.3387 - dense_29_loss: 0.3429 - dense_30_loss: 0.3444 - dense_31_loss: 0.3440 - dense_32_loss: 0.3539 - dense_33_loss: 0.3472 - dense_34_loss: 0.3457 - dense_35_loss: 0.3479 - dense_36_loss: 0.3467 - dense_37_loss: 0.3481 - dense_38_loss: 0.3496 - dense_39_loss: 0.3450 - dens

Epoch 00003: early stopping


In [ ]:
quizzes = Xtest.argmax(3)  # quizzes in the (?, 9, 9) shape. From the test set
true_grids = ytest.argmax(3) + 1  # true solutions dont forget to add 1 
smart_guesses = batch_smart_solve(quizzes, solver)  # make smart guesses !

deltas = diff(true_grids, smart_guesses)  # get number of errors on each quizz
accuracy = (deltas == 0).mean()  # portion of correct solved quizzes

In [ ]:
print(
"""
Grid solved:\t {}
Correct ones:\t {}
Accuracy:\t {}
""".format(
deltas.shape[0], (deltas==0).sum(), accuracy
)
)